name: leanring github action
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

env:
  ISSUE_NUM: ${{ github.event.issue.number }}

jobs:

  checkout-code:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'edited')

    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    
    - name: regex match issue body 
      id: domain-match
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ github.event.issue.body }}
        regex: 'Domain:\s*(.+)$'
        flags: 'mg'

    
    - name: comment-on-issue
      id: comment-on-issue
      if: ${{ steps.domain-match.output.match != '' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ env.ISSUE_NUM }}
        body: "congrats! issue opened with proper format ${{ steps.domain-match.outputs.group1 }}"
    
    - name: comment-on-issue-part-2  
      id: comment-on-issue-2
      if: ${{ steps.domain-match.output.match == '' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ env.ISSUE_NUM }}
        body: "issue opened is not in proper format!"





    

