name: comment-on-issue
on:
  issues:
    types: [opened, edited]

  workflow_dispatch:

env:
  ISSUE_NUM: ${{ github.event.issue.number }}

jobs:

  hello-world:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    if: github.event_name== 'issues' && (github.event.action == 'opened' || github.event.action == 'edited')

    steps:

      - name: checkout
        id: checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
          
      - name: comment-on-issue
        id: comments
        run: |
          comment="Hello from this Issue $ISSUE_NUM"
          echo "issue_comment=$comment" >> $GITHUB_OUTPUT
      
      - name: comment on an issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ env.ISSUE_NUM }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.comments.outputs.issue_comment }}
          reactions: eyes
